version: '3'

services:
  gateway:
    image: "registry.gitlab.com/zxtang/gateway:1.0.0"
    restart: always
    volumes:
      - "./conf/gateway.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/gateway/log:/var/log:z"
    ports:
      - "10443:443"
      - "8899:80"
    environment:
      - ENV

  auth:
    image: "registry.gitlab.com/zxtang/auth:1.0.0"
    restart: always
    volumes:
      - "./conf/auth.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/auth/log:/var/log:z"
    environment:
      - ENV

  authdb:
    image: "registry.gitlab.com/zxtang_db/auth:1.0.0"
    restart: always
    volumes:
      # 数据目录挂载到宿主机
      - "./.runtime/authdb/postgresql/data:/var/lib/postgresql/data"
    env_file:
      - runtime.env
    environment:
      - POSTGRES_DB=authdb
    ports:
      - "15432:5432"

  merchant:
    image: "registry.gitlab.com/zxtang/merchant:1.0.0"
    restart: always
    volumes:
      - "./conf/merchant.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/merchant/log:/var/log:z"
    environment:
      - ENV

  merchantdb:
    image: "registry.gitlab.com/zxtang_db/merchant:1.0.0"
    restart: always
    volumes:
      # 数据目录挂载到宿主机
      - "./.runtime/merchantdb/postgresql/data:/var/lib/postgresql/data"
    env_file:
      - runtime.env
    environment:
      - POSTGRES_DB=merchantdb
    ports:
      - "25432:5432"

  article:
    image: "registry.gitlab.com/zxtang/article:1.0.0"
    restart: always
    volumes:
      - "./conf/article.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/article/log:/var/log:z"
    environment:
      - ENV

  articledb:
    image: "registry.gitlab.com/zxtang_db/article:1.0.0"
    restart: always
    volumes:
      # 数据目录挂载到宿主机
      - "./.runtime/articledb/postgresql/data:/var/lib/postgresql/data"
    env_file:
      - runtime.env
    environment:
      - POSTGRES_DB=articledb
    ports:
      - "35432:5432"

  like:
    image: "registry.gitlab.com/zxtang/like:1.0.0"
    restart: always
    volumes:
      - "./conf/like.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/like/log:/var/log:z"
    environment:
      - ENV
    
  likedb:
    image: "registry.gitlab.com/zxtang_db/like:1.0.0"
    restart: always
    volumes:
      # 数据目录挂载到宿主机
      - "./.runtime/likedb/postgresql/data:/var/lib/postgresql/data"
    env_file:
      - runtime.env
    environment:
      - POSTGRES_DB=likedb
    ports:
      - "45432:5432"

  file:
    image: "registry.gitlab.com/zxtang/file:1.0.0"
    restart: always
    volumes:
      - "./conf/file.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/file/log:/var/log:z"
      - "/data/upload:/data/upload:z"
    environment:
      - ENV

  comment:
    image: "registry.gitlab.com/zxtang/comment:1.0.0"
    restart: always
    volumes:
      - "./conf/comment.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/comment/log:/var/log:z"
    environment:
      - ENV
      

  commentdb:
    image: "registry.gitlab.com/zxtang_db/comment:1.0.0"
    restart: always
    volumes:
      # 数据目录挂载到宿主机
      - "./.runtime/commentdb/postgresql/data:/var/lib/postgresql/data"
    env_file:
      - runtime.env
    environment:
      - POSTGRES_DB=commentdb
    ports:
      - "55432:5432"

  stypes:
    image: "registry.gitlab.com/zxtang/stypes:1.0.0"
    restart: always
    volumes:
      - "./conf/stypes.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/stypes/log:/var/log:z"
    environment:
      - ENV

  stypesdb:
    image: "registry.gitlab.com/zxtang_db/stypes:1.0.0"
    restart: always
    volumes:
      # 数据目录挂载到宿主机
      - "./.runtime/stypesdb/postgresql/data:/var/lib/postgresql/data"
    env_file:
      - runtime.env
    environment:
      - POSTGRES_DB=stypesdb
    ports:
      - "65432:5432"

  souldb:
    image: "registry.gitlab.com/zxtang_db/soul:1.0.0"
    restart: always
    volumes:
      # 数据目录挂载到宿主机
      - "./.runtime/souldb/postgresql/data:/var/lib/postgresql/data"
    env_file:
      - runtime.env
    environment:
      - POSTGRES_DB=souldb
    ports:
      - "65433:5432"
  
  vwood:
    image: "registry.gitlab.com/zxtang/vwood:1.0.0"
    restart: always
    volumes:
      - "./.runtime/vwood/log:/var/log:z"
    environment:
      - ENV
    ports:
      - "3000:3000"