version: '3'

services:
  gateway:
    image: "abelce/gateway:1.0.0"
    restart: always
    volumes:
      - "./conf/gateway.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/gateway/log:/var/log:z"
    ports:
      - "10443:443"
      - "8899:80"
    environment:
      - ENV

  auth:
    image: "abelce/auth:1.0.0"
    restart: always
    volumes:
      - "./conf/auth.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/auth/log:/var/log:z"
    environment:
      - ENV

  authdb:
    image: "abelce/auth_db:1.0.0"
    restart: always
    volumes:
      # 数据目录挂载到宿主机
      - "./.runtime/authdb/postgresql/data:/var/lib/postgresql/data"
    env_file:
      - runtime.env
    environment:
      - POSTGRES_DB=authdb
    ports:
      - "15432:5432"

  merchant:
    image: "abelce/merchant:1.0.0"
    restart: always
    volumes:
      - "./conf/merchant.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/merchant/log:/var/log:z"
    environment:
      - ENV

  merchantdb:
    image: "abelce/merchant_db:1.0.0"
    restart: always
    volumes:
      # 数据目录挂载到宿主机
      - "./.runtime/merchantdb/postgresql/data:/var/lib/postgresql/data"
    env_file:
      - runtime.env
    environment:
      - POSTGRES_DB=merchantdb
    ports:
      - "25432:5432"

  article:
    image: "abelce/article:1.0.0"
    restart: always
    volumes:
      - "./conf/article.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/article/log:/var/log:z"
    environment:
      - ENV

  articledb:
    image: "abelce/article_db:1.0.0"
    restart: always
    volumes:
      # 数据目录挂载到宿主机
      - "./.runtime/articledb/postgresql/data:/var/lib/postgresql/data"
    env_file:
      - runtime.env
    environment:
      - POSTGRES_DB=articledb
    ports:
      - "35432:5432"

  like:
    image: "abelce/like:1.0.0"
    restart: always
    volumes:
      - "./conf/like.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/like/log:/var/log:z"
    environment:
      - ENV
    
  likedb:
    image: "abelce/like_db:1.0.0"
    restart: always
    volumes:
      # 数据目录挂载到宿主机
      - "./.runtime/likedb/postgresql/data:/var/lib/postgresql/data"
    env_file:
      - runtime.env
    environment:
      - POSTGRES_DB=likedb
    ports:
      - "45432:5432"

  file:
    image: "abelce/file:1.0.0"
    restart: always
    volumes:
      - "./conf/file.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/file/log:/var/log:z"
      - "/data/upload:/data/upload:z"
    environment:
      - ENV

  comment:
    image: "abelce/comment:1.0.0"
    restart: always
    volumes:
      - "./conf/comment.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/comment/log:/var/log:z"
    environment:
      - ENV

  commentdb:
    image: "abelce/comment_db:1.0.0"
    restart: always
    volumes:
      # 数据目录挂载到宿主机
      - "./.runtime/commentdb/postgresql/data:/var/lib/postgresql/data"
    env_file:
      - runtime.env
    environment:
      - POSTGRES_DB=commentdb
    ports:
      - "55432:5432"

  stypes:
    image: "abelce/stypes:1.0.0"
    restart: always
    volumes:
      - "./conf/stypes.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/stypes/log:/var/log:z"
    environment:
      - ENV

  stypesdb:
    image: "abelce/stypes_db:1.0.0"
    restart: always
    volumes:
      # 数据目录挂载到宿主机
      - "./.runtime/stypesdb/postgresql/data:/var/lib/postgresql/data"
    env_file:
      - runtime.env
    environment:
      - POSTGRES_DB=stypesdb
    ports:
      - "65432:5432"

  # souldb:
  #   image: "registry.gitlab.com/zxtang_db/soul:1.0.0"
  #   restart: always
  #   volumes:
  #     # 数据目录挂载到宿主机
  #     - "./.runtime/souldb/postgresql/data:/var/lib/postgresql/data"
  #   env_file:
  #     - runtime.env
  #   environment:
  #     - POSTGRES_DB=souldb
  #   ports:
  #     - "65433:5432"
  
  # vwood:
  #   image: "abelce/vwood:1.0.0"
  #   restart: always
  #   volumes:
  #     - "./.runtime/vwood/log:/var/log:z"
  #   environment:
  #     - ENV
  #   ports:
  #     - "3000:3000"
  
  email:
    image: "abelce/email:1.0.0"
    restart: always
    volumes:
      - "./conf/email.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/email/log:/var/log:z"
    environment:
      - ENV

  product:
    image: "abelce/product:1.0.0"
    restart: always
    volumes:
      - "./conf/product.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/product/log:/var/log:z"
    environment:
      - ENV

  productdb:
    image: "abelce/product_db:1.0.0"
    restart: always
    volumes:
      # 数据目录挂载到宿主机
      - "./.runtime/productdb/postgresql/data:/var/lib/postgresql/data"
    env_file:
      - runtime.env
    environment:
      - POSTGRES_DB=productdb
    ports:
      - "65434:5432"
  
  productapi:
    image: "abelce/productapi:1.0.0"
    restart: always
    volumes:
      - "./conf/productapi.json:/go/bin/config.json"
      - "./ssl:/go/bin/ssl:z"
      - "./.runtime/productapi/log:/var/log:z"
    environment:
      - ENV
  
  # webdb:
  #   image: "abelce/websites_db:1.0.0"
  #   restart: always
  #   volumes:
  #     # 数据目录挂载到宿主机
  #     - "./.runtime/webdb/postgresql/data:/var/lib/postgresql/data"
  #   env_file:
  #     - runtime.env
  #   environment:
  #     - POSTGRES_DB=webdb
  #   ports:
  #     - "65435:5432"
  
  # web:
  #   image: "abelce/websites:1.0.0"
  #   restart: always
  #   volumes:
  #     - "./conf/web.json:/go/bin/config.json"
  #     - "./ssl:/go/bin/ssl:z"
  #     - "./.runtime/web/log:/var/log:z"
  #   environment:
  #     - ENV